apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv
  namespace: wordpress-namespace
  labels:
    app: wordpress
spec:
  capacity:
    storage: 2Gi  # Define the storage capacity for WordPress
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce  # Access mode to mount WordPress for a single pod
  persistentVolumeReclaimPolicy: Retain  # Retain the PV when the PVC is deleted
  storageClassName: manual  # Storage class that matches the cluster's storage configuration
  hostPath:
    path: /mnt/data/wordpress  # Local disk path on the node for WordPress storage
    type: DirectoryOrCreate