apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: wordpress-hpa
  namespace: wordpress-namespace
  labels:
    app: wordpress
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: wordpress  # Targeting the WordPress deployment
  minReplicas: 1  # Value for minimum replicas (pods)
  maxReplicas: 5  # Value for maximum replicas (pods)
  metrics:
    - type: Resource
      resource:
        name: cpu  # Base for scaling based on CPU usage
        target:
          type: Utilization
          averageUtilization: 50  # Scale up if CPU utilization exceeds 50%