apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
  namespace: wordpress-namespace
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce  # Read-write access for WordPress for one pod
  resources:
    requests:
      storage: 2Gi  # Storage size requested for WordPress
  volumeMode: Filesystem
  storageClassName: manual  # Must match the PV storage class
  volumeName: wordpress-pv  # Link the PVC to the specific PV