version: '3.8'

services:
  mysql:
    image: sholly333/sholly333-mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  wordpress:
    image: holly333/holly333-wordpress:latest
    container_name: wordpress
    ports:
      - "8100:80"
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      - mysql

volumes:
  mysql_data:
