apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config  # This name should match the name of the StatefulSet
  namespace: wordpress-namespace
data:
  MYSQL_DATABASE: wordpress
  MYSQL_USER: wordpress