apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret  # This name should match the environment variable in the StatefulSet; only then will the pod be ready and there won't be an error in 'kubectl get all'
  namespace: wordpress-namespace
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk  # Base64 for "rootpassword"
  MYSQL_PASSWORD: d29yZHByZXNzCg==  # Base64 for "wordpress"
  WORDPRESS_DB_PASSWORD: d29yZHByZXNzCg==  # Base64 for "wordpress" (add this line)