# Use the official MySQL image
FROM mysql:5.7

# Environment variables for MySQL setup
ENV MYSQL_ROOT_PASSWORD=some_password_of_ur_choice
ENV MYSQL_DATABASE=name_your_wordpress_database
ENV MYSQL_USER=wordpress_user
ENV MYSQL_PASSWORD=wordpress_user_password

# Volume for persistent data
VOLUME /var/lib/mysql

